config/routes.rb
Rails.application.routes.draw do
  resources :quests
  post 'toggle', to: 'quests#toggle'

  root to: "quests#index"

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/completion.rb
class Completion < ApplicationRecord
  belongs_to :quest

  validates :quest, presence: true
  validates :date_completed, uniqueness: {scope: :quest_id}
end

app/models/concerns/defaults.rb
require 'active_support/concern'

module Defaults
  extend ActiveSupport::Concern

  # Added to instance of object
  included do
    after_initialize :apply_default_values
  end

  # Callback for setting default values
  def apply_default_values
    self.class.defaults.each do |attribute, param|
      next unless self.send(attribute).nil?
      value = param.respond_to?(:call) ? param.call(self) : param
      self[attribute] = value
    end
  end

  # Added to class of object
  class_methods do
    def default(attribute, value = nil, &block)
      defaults[attribute] = value
      # Allow the passing of blocks
      defaults[attribute] = block if block_given?
    end

    def defaults
      @defaults ||= {}
    end
  end
end

app/models/quest.rb
class Quest < ApplicationRecord
  include Defaults
  belongs_to :user
  has_many :completions

  validates_presence_of :user, :description
  validates :goal, numericality: { only_integer: true }, allow_nil: true
  validates :goal, presence: true, if: "reward.present?"

  default :complete, false

  def chain(from_date: DateTime.now)
    prev_date = nil
    chain = 0
    self.completions.where("created_at <= :from_date", {from_date: from_date}).order(created_at: :desc).each_with_index do |completion, index|
      # If this quest hasn't been completed in the last 24 hours, consider the chain broken
      if completion.created_at < from_date - 24.hours && index == 0
        break
      end

      # Latest completion
      if prev_date.nil?
        chain = chain + 1
        prev_date = completion.date_completed

        next
      end

      # Look back through completions until we find a gap
      completion_date = completion.date_completed
      if prev_date.yesterday == completion_date
        chain = chain + 1
        prev_date = completion_date
      else
        break
      end
    end

    chain
  end

  #Look back through completions to determine the longest chain.
  def longest_chain
    max_length = 0
    prev_date = nil

    self.completions.order(created_at: :desc).each do |completion|
      # Skip completions that are part of the same chain.
      if prev_date.nil? || prev_date.yesterday != completion.date_completed
        chain_length = self.chain(from_date: completion.created_at)

        max_length = chain_length if chain_length > max_length
      end

      prev_date = completion.date_completed
    end

    max_length
  end

  def toggle_completion
    today = Date.today
    completion = self.completions.where(date_completed: today).first

    result = true
    if completion.nil?
      self.completions.create(date_completed: today)
    else
      completion.destroy
      result = false
    end

    result
  end

  def complete_today?
    self.completions.where(date_completed: Date.today).present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :quests

  def active_quests
    self.quests.where(complete: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized(exception)
    flash[:alert] = exception.message || "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :authenticate_user!

  def index
    @quests = policy_scope(Quest)
  end

  def new
    @quest = Quest.new
  end

  def create
    @quest = Quest.new(quest_params)
    @quest.user = current_user
    authorize @quest

    if @quest.save
      redirect_to quests_path
    else
      render 'new'
    end
  end

  def edit
    @quest = authorize Quest.find(params[:id])
  end

  def update
    @quest = authorize Quest.find(params[:id])

    if @quest.update(quest_params)
      redirect_to quests_path
    else
      render 'edit'
    end
  end

  def destroy
    @quest = authorize Quest.find(params[:id])
    @quest.destroy

    redirect_to quests_path
  end

  def toggle
    @quest = authorize Quest.find(params[:id]), :update?

    @completed = @quest.toggle_completion

    respond_to do |format|
      format.html { redirect_to quests_path, notice: "Quest completed!" }
      format.js
    end
  end

  private
    def quest_params
      params.require(:quest).permit(:description, :goal, :reward)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/views/bootstrap3_form_builder/_error_messages.html.erb
<% if target.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <strong>
            <%= "#{pluralize(target.errors.count, "error")} prohibited this from being saved:" %>
        </strong>
        <ul>
            <% target.errors.full_messages.each do |msg| %>
                <li>
                    <%= msg %>
                </li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DailyQuest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.12/datatables.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Lora|Open+Sans:800" rel="stylesheet">
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.12/datatables.min.js"></script>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to root_path, class: "navbar-brand" do %>
                <span style="color: blue; font-weight: bold; font-family: fantasy;">!</span>Daily Quests
              <% end %>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
              <ul class="nav navbar-nav navbar-right">
                <%= render partial: "devise/menu/login_items" %>
                <%= render partial: "devise/menu/registration_items" %>
              </ul>
            </div>
          </div>
        </nav>
      </div>
      <div class="row">
        <% if notice %>
          <p class="alert alert-info"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/quests/_form.html.erb
<div class="row">
  <%= bootstrap_form_for @quest, url: { action: action } do |f| %>
      <%= f.text_field :description, help_block: 'A quest must have a purpose.' %>
      <%= f.text_field :reward, help_block: 'Optional. What treasure or leisure awaits you at the end?' %>
      <%= f.text_field :goal, help_block: 'Optional, unless you specify a reward. How many days must you complete this quest for the reward?' %>
      <%= f.submit "Sail to Glory", class: "btn btn-primary" %>
      <% if action == 'update' %>
        <%= link_to 'Destroy', quest_path(@quest), method: :delete, data: {confirm: 'Are you sure you wish to disembark this quest, forever?'}, class: "btn btn-danger" %>
      <% end %>
      <%= link_to 'Back', quests_path, class: 'btn btn-default' %>
  <% end %>
</div>

app/views/quests/edit.html.erb
<div class="row">
  <h1>Alter the Terms of your Quest</h1>
</div>
<div class="row">
  <%= render partial: "form", locals: { action: "update" } %>
</div>
<div class="row">
  <h2>Completion Calendar</h2>
</div>
<div class="row">
  <%= month_calendar events: @quest.completions, attribute: :date_completed do |date, completions| %>
    <%= date.day %>
    <% completions.each do %>
      <div class="full-circle"></div>
    <% end %>
  <% end %>
</div>

app/views/quests/index.html.erb
<div class="row">
  <h1>
    <span style="color: blue; font-weight: bold; font-family: fantasy;">!</span>Daily Quests
  </h1>
</div>

<div class="row">
  <div id="intro">
    <p>
      Daily quests are to-do lists for your life. They are activities that you want to become routine.
      They should contribute to your life goals and long term happiness.
    </p>
    <p>
      Build your quest log here, and check it every day to remind yourself of what you should be doing.
      Tick off quests as you complete them each day. Completing quests on consecutive days will build an ever higher
      chain score.
    </p>
  </div>
</div>

<div class="row">
  <%= link_to 'Embark on a New Quest!', new_quest_path, class: 'btn btn-success' %>
</div>

<% unless @quests.empty? %>
  <div class="row">
    <div class="table-container">
      <table class="table" id="quest-table">
        <thead>
        <th>Description</th>
        <th>Goal</th>
        <th>Reward</th>
        <th>Current Chain</th>
        <th>Longest Chain</th>
        <th>Total Completions</th>
        <th>Complete Today</th>
        </thead>
        <tbody>
        <% @quests.each do |quest| %>
          <tr>
            <td>
              <%= link_to quest.description, edit_quest_path(quest.id) %>
            </td>
            <td><%= quest.goal %></td>
            <td><%= quest.reward %></td>
            <td id="<%= quest.id %>_chain"><%= quest.chain %></td>
            <td id="<%= quest.id %>_longest"><%= quest.longest_chain %></td>
            <td id="<%= quest.id %>_completions"><%= quest.completions.size %></td>
            <td>
              <%= check_box_tag 'complete', quest.id, quest.complete_today?,
                                data: {
                                    remote: true,
                                    url: url_for(action: :toggle, id: quest.id),
                                    method: 'POST'
                                }
              %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <blockquote id="quote">
      <p>We are what we repeatedly do. Excellence, then, is not an act, but a habit.</p>
      <footer>Aristotle</footer>
     </blockquote>
  </div>
  <div class="modal fade" id="rewardModal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Reward Unlocked!</h4>
        </div>
        <div class="modal-body">
          Congratulations, you set a goal to complete this quest <strong><span id="goalModalText"></span></strong> times, and you just did.
          Your reward for completing this quest is <strong><span id="rewardModalText"></span></strong>.
        </div>
        <div class="modal-footer">
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/quests/new.html.erb
<div class="row">
  <h1>Take On A New Quest</h1>
</div>
<%= render partial: "form", locals: { action: "create" } %>

app/views/quests/show.html.erb
<h1>Quest#show</h1>
<p>Find me in app/views/quest/show.html.erb</p>

app/views/quests/toggle.js.erb
var $chain_cell = $("#<%= @quest.id %>_chain");
var $completion_cell = $("#<%= @quest.id %>_completions");
var $longest_cell = $("#<%= @quest.id %>_longest");

$chain_cell.text(<%= @quest.chain %>);
$completion_cell.text(<%= @quest.completions.count %>);
$longest_cell.text(<%= @quest.longest_chain %>);

var completions = <%=@quest.completions.size %>;
var goal_met = completions % <%= @quest.goal.present? ? @quest.goal : 0 %> === 0;
var goal_present = <%= @quest.goal.present? %>;
var complete_today = <%= @quest.complete_today? %>;

if( complete_today && completions != 0 && goal_met && goal_present) {
  $("#rewardModalText").text("<%= @quest.reward %>");
  $("#goalModalText").text(<%= @quest.goal %>);
  $(".modal-footer").html('<%= link_to "Update Reward", edit_quest_path(@quest), class: "btn btn-primary" %>');
  $(".modal-footer").append('<%= link_to 'End Quest', quest_path(@quest), method: :delete, data: {confirm: 'Are you sure you wish to disembark this quest, forever?'}, class: "btn btn-danger" %>');
  $("#rewardModal").modal('show');
}